name: DeployGHPages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - run: ls
      - run: npm run build
