name: DeployGHPages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - run: ls
      - run: sudo ./node_modules/vuepress/cli.js build
      - run: cd .vuepress/dist
      - run: echo "bn.mlmodel.fit" > CNAME
      - run: git init
      - run: git add -A
      - run: git config --global user.email "manashmndl@gmail.com"
      - run: git config --global user.name "manashmandal"
      - run: git commit -m "Deploy"
      - run: git push -f https://manashmandal:${{ secrets.GITHUB_TOKEN }}@github.com/manashmandal/bn.mlmodel.fit.git master:gh-pages
